### ISSUE TITLE
not package in pypi

### ISSUE THREAD

**Issue by dicos** [originell/sorl-watermark#1]
in docs write: "or by installing it via pip:"

In my console:
$ pip install sorl-watermark
Downloading/unpacking sorl-watermark
  Could not find any downloads that satisfy the requirement sorl-watermark
No distributions at all found for sorl-watermark
Storing complete log in /home/dmitry/.pip/pip.log

**Comment by originell** [comment]
welcome back @vbazhin  :)

**Comment by vbazhin** [comment]
Hi Luis! Nice to hear you again.)

**Comment by vbazhin** [comment]
Just having some free time, so decided to bring the repo up to date.
