### ISSUE TITLE
IOError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by liuxue0905** [originell/sorl-watermark#28]
watermark is 'watermarks/mark.png', mark.png is same as sorl-watermark/tests

no matter my picture on web page is jpeg or png

```
Request Method: | GET
-- | --
http://localhost:8888/portal/records/
1.11.3
IOError
cannot write mode RGBA as JPEG
/usr/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py in _save, line 604
/usr/local/opt/python/bin/python2.7
2.7.13
['/Users/liuxue/PycharmProjects/GoldenTimes',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',  '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/site-packages/onvif-0.1.3-py2.7.egg',  '/usr/local/lib/python2.7/site-packages/WSDiscovery-0.2-py2.7.egg',  '/usr/local/Cellar/numpy/1.13.0/libexec/nose/lib/python2.7/site-packages']
Mon, 11 Sep 2017 01:23:11 +0000
```

**Comment by lampslave** [comment]
https://github.com/python-pillow/Pillow/issues/2609

**Comment by liuxue0905** [comment]
Problem of Pillow 4.2
```
$ pip install "Pillow<4.2"
```

**Comment by liuxue0905** [comment]
I try sorl-watermark, i think it's better than django-watermark.

**Comment by killown** [comment]
not fixed yet?

**Comment by developer-mayuan** [comment]
I have the same error using Pillow 5.0

**Comment by originell** [comment]
Ah. I don't yet use Pillow 5 in any production environment. Sadly, I don't have time to look at this in the coming days. But I'll schedule some time next week.

**Comment by vbazhin** [comment]
Hi @originell :)
I'm here too, and possibly I'll have some time on Sunday to look at this, but not sure yet.

**Comment by originell** [comment]
@vbazhin Awesome! If you find the time test that, let me know. Otherwise I will just try to schedule an hour or so next week.

**Comment by vbazhin** [comment]
Hi @originell . I had a short time to investigate this tonight.
The tests pass on my end for py2.7+django1.10+Pillow5 and py3.4+django1.10+Pillow5.
I couldn't reproduce the problem so far. 
Just a rough presumption: maybe, the behavior may vary depending on different libjpeg versions?

**Comment by originell** [comment]
Thanks for testing this! maybe! @developer-mayuan can you tell us which libjpeg version you are using?

**Comment by emacsway** [comment]
I've the same problem with Pillow==5.1.0

**Comment by emacsway** [comment]
there is a workaround https://github.com/biz-tek-dev/sorl-watermark/commit/314149f09567d5c195c9e02cc60c9361f53baa77

**Comment by emacsway** [comment]
there is a workaround https://github.com/biz-tek-dev/sorl-watermark/commit/e587a61c50a6bc32a5efa057fb43e86fe90f5428

**Comment by originell** [comment]
Good catchs @emacsway .. @vbazhin do you have time to integrate this? BUT we shouldn't simply convert to RGB without first checking that we are processing an RGB image (JPG)

**Comment by emacsway** [comment]
> BUT we shouldn't simply convert to RGB without first checking that we are processing an RGB image (JPG)

Oh, you are right, thanks.
