### ISSUE TITLE
Syntax error with python 3.6

### ISSUE THREAD

**Issue by patelrajnath** [originell/sorl-watermark#30]
Hi, I'm trying to use image watermark with sorl-thumbnail. But when I add it in app settings it complaints for the following syntax error-

```
    from sorl_watermarker.engines.base import WatermarkEngineBase
  File "/home/raj/.local/lib/python3.6/site-packages/sorl_watermarker/engines/base.py", line 80
    except TypeError, e:
                    ^
SyntaxError: invalid syntax
```
My settings
```
THUMBNAIL_ENGINE = 'sorl_watermarker.engines.pil_engine.Engine'
THUMBNAIL_WATERMARK = 'display/avatar/anyone.png' (This is in static dir of my application)
```
Please suggest. Thank you.

**Comment by originell** [comment]
Hey @patelrajnath .. as it seems we have [fixed this syntax issue](https://github.com/originell/sorl-watermark/blob/master/sorl_watermarker/engines/base.py#L82) already. Could you try simply using the latest git master?

**Comment by originell** [comment]
hey @patelrajnath we are in the process of publishing a new release, which will land soon (#31). 

Until then you can use the latest git master. It fixes the issue. I personally tried 3.5 to 3.7 and it's working nicely. I'm closing this issue now.
