### ISSUE TITLE
Re-add my pypi rights

### ISSUE THREAD

**Issue by originell** [originell/sorl-watermark#31]
Hey @vbazhin I just noticed that I don't have any rights on pypi anymore to publish. 

I just updated some stuff. So it would be awesome if you could re-grant me those rights ;-) 

thanks and hope you are well!

**Comment by originell** [comment]
bumb @vbazhin

**Comment by meshy** [comment]
It's been over a year since this ticket was opened, and there appears to be no response. Have there been any significant changes since 1.0 that warrant a release? (Support for newer versions of Django, perhaps?) If so, might it make sense at this point to release to a new name on PyPI?

**Comment by originell** [comment]
Well yeah, I added proper JPG/RGB support with  91809e37d9b760690dab43aab4b936a180cbb61a, which allows for supporting newer sorl-thumbnail/Pillow requirements. Also, improved error messages.

I'll try to contact pypi support.. maybe they can help. Otherwise I guess releasing under a new name is the only other option 

thanks for the heads up. Were you planning on using the pypi release?

**Comment by meshy** [comment]
> Well yeah, I added proper JPG/RGB support with 91809e3, which allows for supporting newer sorl-thumbnail/Pillow requirements. Also, improved error messages.

Good to know, thanks.

> I'll try to contact pypi support.. maybe they can help. Otherwise I guess releasing under a new name is the only other option

:+1: 

> Were you planning on using the pypi release?

I'm working on reviving an old codebase. I wasn't sure what the supported versions of Django are on the 1.0 release, and didn't like the idea of pinning a commit from github if I could help it, so was investigating my options!

Thank you for the quick response :)

**Comment by meshy** [comment]
@originell @vbazhin I wonder if there's been any progress on this?

**Comment by originell** [comment]
Hey @meshy! sorry, not yet. I'm afraid you might have to pin to the github commit for now.

If you'd like I can highlight you once I can continue here.

**Comment by meshy** [comment]
Hey! :) That would be good, thanks. And thanks again for the quick reply!

**Comment by originell** [comment]
update: I was able to contact vbazhin and got back the pypi rights.

time for updates!

**Comment by originell** [comment]
@meshy fyi v1.2.0 is released now :)

**Comment by meshy** [comment]
Thanks for the heads up! I no longer work at the company that needed this update, but I'm glad you got it sorted!
