### ISSUE TITLE
Is it possible to revert watermarks from images?

### ISSUE THREAD

**Issue by HoshiYamazaki** [originell/sorl-watermark#32]
As title says.

**Comment by originell** [comment]
Hey hoshi! 

You mean after they are already put onto the image? I'm afraid not via this package.

Removal of watermarks is an entirely different beast. You might have more luck googling for "removal watermark machine learning". I remember there [was some work on that front](https://kinja.com/api/profile/getsession?redirect=https%3A%2F%2Fgizmodo.com%2Fsetsession%3Fr%3Dhttps%253A%252F%252Fgizmodo.com%252Fnvidia-taught-an-ai-to-flawlessly-erase-watermarks-from-1827474196).

**Comment by originell** [comment]
If this was helpful, please close the isuse :-)
